### ISSUE TITLE
我下载了工程，但是运行不了，请问有啥需要的环境吗

### ISSUE THREAD

**Issue by 17702513221** [HeartlessLD/UE4-OpenCV_Dlib_Plugin#1]
我是虚幻4.24，VS2017
![5GAJSL6T8WX _JO4U%3F}X](https://user-images.githubusercontent.com/40785359/89614709-92b26100-d8b7-11ea-8740-30e5e4fc77b1.png)
zhe这是我的错误

**Comment by HeartlessLD** [comment]
没有什么特殊的环境，基本上就是配置好opencv的库就可以了，你这个错误感觉是opencv库没配置对，在检测一下是不是缺少什么dll lib，可以参考我的csdn链接里的添加步骤




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HeartlessLD/UE4-OpenCV_Dlib_Plugin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午2:09
收件人:&nbsp;"HeartlessLD/UE4-OpenCV_Dlib_Plugin"<UE4-OpenCV_Dlib_Plugin@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HeartlessLD/UE4-OpenCV_Dlib_Plugin] 我下载了工程，但是运行不了，请问有啥需要的环境吗 (#1)





 
我是虚幻4.24，VS2017
 
 zhe这是我的错误

**Comment by 17702513221** [comment]
我成功了，需要进VS2017先编译一下，请问使用rtsp摄像头是在蓝图里改还是去源码改

**Comment by HeartlessLD** [comment]
工程默认是通过opencv 的摄像头库去调用的，你可以找到对应的源码位置，去修改




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "谢晟"<notifications@github.com&gt;; 
发送时间: 2020年8月7日(星期五) 下午3:06
收件人: "HeartlessLD/UE4-OpenCV_Dlib_Plugin"<UE4-OpenCV_Dlib_Plugin@noreply.github.com&gt;; 
抄送: "镜月"<997146918@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HeartlessLD/UE4-OpenCV_Dlib_Plugin] 我下载了工程，但是运行不了，请问有啥需要的环境吗 (#1)





 
我成功了，需要进VS2017先编译一下，请问使用rtsp摄像头是在蓝图里改还是去源码改

**Comment by 17702513221** [comment]
能加个QQ好友吗，406174050，难得抱到大腿

**Comment by HeartlessLD** [comment]
我就是刚好做到这个项目，了解了一点，其他的也不懂&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "谢晟"<notifications@github.com&gt;; 
发送时间: 2020年8月7日(星期五) 下午3:09
收件人: "HeartlessLD/UE4-OpenCV_Dlib_Plugin"<UE4-OpenCV_Dlib_Plugin@noreply.github.com&gt;; 
抄送: "镜月"<997146918@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HeartlessLD/UE4-OpenCV_Dlib_Plugin] 我下载了工程，但是运行不了，请问有啥需要的环境吗 (#1)





 
能加个QQ好友吗，406174050，难得抱到大腿
